<?php
use Laminas\Http\Client;
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$template = $item->resourceTemplate();
$alleToepassingen = array('onderbouw','draagstructuur','isolatie (thermisch)','isolatie (akoestisch)','ventilatie','constructie - wand', 'constructie - vloer', 'constructie - dak', 'afwerking - wand (binnen)','afwerking - wand (buiten)','afwerking - vloer','afwerking - plafond','afwerking - coatings','afwerking - dak','binnenschrijnwerk','buitenschrijnwerk','inrichting - meubilair','inrichting - textiel','bevestiging- en verwerkingsmateriaal','verwarming en koeling','elektriciteit','sanitair');
if($template):
  $type = $template->label();
else:
  $type = "";
endif;
?>

<style>
  .slick-prev:before,
  .slick-next:before {
    color: #007bff;
    font-size: 25px;
  }
  .slick-next{
    right: 0px;
  }
  #carousel::before {
    line-height: 1;
    display: inline-block;
    content: '';
  }
  .slider-for .slick-slide img {
    max-height: fit-content;
  }
</style>

<div class="container">
  <div>
    <div id="portal-breadcrumbs" class="breadcrumbs" style="display:block;padding-top:5%;">
      <span class="breadcrumb-item">
          <a href="<?php echo $site->url();?>">Home</a>
      </span>

      <?php if($type == 'Nieuws'):?>
        <span class="breadcrumb-item" dir="ltr">
          <a href="<?php echo $site->url()."/item/browse?resource_template_id=2";?>">Nieuws</a>
        </span>
      <?php else:?>
        <span class="breadcrumb-item">
          <a href="<?php echo $site->url()."/find";?>">Uitgebreid Zoeken</a>         
        </span>    
      <?php endif;?>
      <span class="breadcrumb-item active">
        <?php echo $item->displayTitle(); ?>
      </span>

    </div>
  </div>
 
  <h1><?php echo $item->displayTitle(); ?></h1>
  <?php if($type == 'Nieuws'):?>
    <!--<h2 class="subtitle is-6"><?php echo date('d-m-Y',strtotime($item->value('dcterms:date'))); ?></h2>-->
  <?php endif;?> 

  <?php
    $viewerlink = '';$fls=[];
  ?>

  <?php if($type == 'Nieuws'):?>
    <div class="columns">
    <?php if (!$embedMedia && $itemMedia): ?>
      <div class="col-4">
        <?php if(sizeof($itemMedia) > 1):?>
          <div class="slider-for">
            <?php foreach($itemMedia as $media):?>
              <div class="has-text-centered">
                <?php $url = str_replace('http:', '', $media->thumbnailUrl('large'));?>
                  <img src="<?php echo $url;?>">
                <?php if($media->value('dcterms:title')):?>
                  <figcaption>
                    <?php echo $media->value('dcterms:title');?>
                  </figcaption>
                <?php endif;?>
              </div>
            <?php endforeach;?>
          </div>
        <?php else: ?>
          <div class="beeld">
            <?php $url = str_replace('http:', '', $itemMedia[0]->thumbnailUrl('large'));?>
            <img src="<?php echo $url;?>">
            <?php if($itemMedia[0]->value('dcterms:title')):?>
              <figcaption>
                <?php echo $itemMedia[0]->value('dcterms:title');?>
            </figcaption>
            <?php endif;?>
          </div>
        <?php endif;?>
      </div>
    <?php endif; ?>
    <div class="col-7">
      <div class="text-box content">
        <?php $date =  $item->value('dcterms:date');?>
        <?php if($date):?>
          <?php $date = new DateTime($date->asHtml());?>
          <div style="margin-bottom:0.6rem;color:#666;">
            <?php echo $date->format('d-m-Y');?>
          </div>            
        <?php endif;?> 
        <?php $descs =  $item->value('dcterms:description', array('all' => true));?>
        <?php if($descs):?>
          <?php foreach($descs as $desc):?>
            <div style="margin-top:0.6rem;">
              <?php if ($res = $desc->valueResource()) {?>    
                <div style="background:#eee;padding:0.5rem;font-size:0.9rem;">     
                  <?php if($res->getControllerName() == 'item'): ?>
                      <span>Object</span>                          
                  <?php else:?>   
                      <span>Collectie</span>
                  <?php endif;?> 
                </div>
                <div style="background:#fafafa;padding:1rem;">                  
                  <?php echo $desc->asHtml();?>
                </div>                      
              <?php }elseif($desc->type() == 'uri'){ ?>                      
                  <?php if (strpos($desc->asHtml(), 'blendeff') !== false): ?>
                    <div style="background:#eee;padding:0.5rem;font-size:0.9rem;">
                      <span>Verhaal</span>              
                    </div>  
                  <?php endif;?>              
                <div style="background:#fafafa;padding:1rem;">   
                <div class="icon-text">
                    <span class="icon">
                      <i class="fas fa-chevron-right"></i>
                    </span>
                    <span><?php echo $desc->asHtml();?></span>
                </div>
                </div>
              <?php }else{ ?>                      
                    <?php echo $desc->asHtml();?>
              <?php } ?>
            </div>
          <?php endforeach;?>
        <?php endif;?>
      </div>
    </div>
  </div>
  <?php else:?>
    <div class="row" style="margin-bottom: 2rem;">
    <div class="col-xs-12 col-md-7">
        <span class="text-left"><h3>Vindplaats Gent: <?php echo $item->value('tdc:vindplaats');?></h3></span>
        <?php if ($item->value('tdc:vindplaatsBrussel')): ?>
        <span class="text-left"><h3>Vindplaats Campus Rabot Gent: <?php echo $item->value('tdc:vindplaatsBrussel');?></h3></span>
        <?php endif; ?>
        <div class="text-box card card-gray" style="margin-bottom:0; margin-top:10px;">
          <div style="margin:5%"><?php echo $item->value('tdc:korteBeschrijving');?></div>
          <div style="padding:10%;">
          <?php
                $toepassingen = $item->value('tdc:toepassingen', ['all' => true]);
                foreach ($alleToepassingen as $toep){ 
                    $png = "img/" . $toep . ".png";
                    if (in_array($toep,$toepassingen)): ?>
                    <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:toepassingen][]=<?php echo $toep;?>" data-toggle="tooltip" title="<?php echo $toep;?>" class="badge badge-primary">
                    <img style="width: 34px;height: 34px;" src="<?php echo $this->assetUrl($png);?>">
                    </a>
              <?php else: ?>
                <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:toepassingen][]=<?php echo $toep;?>" data-toggle="tooltip" title="<?php echo $toep;?>" class="badge badge-secondary">
                <img style="width: 34px;height: 34px;" style="opacity: 0.2;" src="<?php echo $this->assetUrl($png);?>">
                </a>
              <?php endif; } ?>
          </div>
        </div>
      </div>
      <?php if (!$embedMedia && $itemMedia): ?>
        <div class="col-xs-12 col-md-5">
          <div id="carousel" class="slider-for slick-slider" style="margin-top: 10px;">
          <?php foreach($itemMedia as $media):?>
            <div class="has-text-centered">
              <?php $url = str_replace('http:', '', $media->thumbnailUrl('large'));?>
              <?php $link = $url;?>
              <?php if($viewerlink):?>
                  <?php $link = $viewerlink;?>
              <?php endif;?> 
              <a target="_blank" href="<?php echo $link;?>"><img src="<?php echo $url;?>"></a>
              <!-- <img src="<?php echo $url;?>"> -->
            </div>
          <?php endforeach;?>
          </div>
          <?php if(count($itemMedia) > 1): ?>
          <div class="slider-nav slick-slider">
          <?php foreach($itemMedia as $media):?>
            <div class="has-text-centered">
              <?php $url = str_replace('http:', '', $media->thumbnailUrl('square'));?>
              <?php $link = $url;?>
              <?php if($viewerlink):?>
                  <?php $link = $viewerlink;?>
              <?php endif;?> 
              <img src="<?php echo $url;?>">
              <!-- <img src="<?php echo $url;?>"> -->
            </div>
          <?php endforeach;?>
          </div>
          <?php endif;?>
        </div>         
      <?php endif;?>
    </div>
    <div class="row">
    <div class="col-xs-12" style="padding-top: 0.50rem;">
        <div class="text-box card card-gray" style="height:100%;margin-bottom:0;">
          <?php echo $item->displayValues(); ?>
        </div>
      </div>
    </div>     
    <?php
      $plugins = $this->getHelperPluginManager();
      $hasNext = $plugins->has('previousResource');
    ?>
    <?php if ($hasNext): ?>
    <div class="previous-next-items">
        <?php if ($previous = $this->previousResource($resource)): ?>
        <?= $previous->link($translate('Previous item'), null, ['class' => 'previous-item']) ?>
        <?php endif; ?>
        <?php if ($next = $this->nextResource($resource)): ?>
        <?= $next->link($translate('Next item'), null, ['class' => 'next-item']) ?>
        <?php endif; ?>
    </div>
    <?php endif; ?>
        </div>
    </section>
<?php endif;?>
<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->subjectValues();
?>
</div>

<?php $this->trigger('view.show.after'); ?>

<script>
  $jq = jQuery.noConflict();
  $jq(document).ready(function(){
    $jq('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: true,
      fade: true,
      centerMode: true
    });
    $jq('.slider-nav').slick({
      slidesToShow: 3,
      slidesToScroll: 1,
      asNavFor: '.slider-for',
      arrows: false,
      centerMode: true,
      focusOnSelect: true,
      centerPadding: '60px'
    });

    $jq('.slide-wrap').on('contextmenu', 'img', function(e){ 
      return false; 
    });
  });
</script>