<?php if($block->dataValue('text')):?>
<section class="section">
<?php else:?>
<section class="section" style="padding-bottom:20px;">
<?php endif?>
    <div class="container">
      <?php if($block->dataValue('title')):?>
        <h3 class="title is-5"><?php echo $block->dataValue('title');?></h3>
      <?php endif;?>
      <div class="columns">
        <?php if($block->dataValue('text') && !$block->dataValue('text2')):?>
          <div class="column is-two-thirds">
            <?php echo $block->dataValue('text');?>
          </div>
        <?php endif;?>
        <?php if($block->dataValue('text') && $block->dataValue('text2')):?>
          <div class="columns">
            <div class="column">
              <?php echo $block->dataValue('text');?>
            </div>
            <div class="column">
              <?php echo $block->dataValue('text2');?>
            </div>
          </div>
        <?php endif;?>
      </div>    
    </div>
</section>
