<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Form\MainSearchForm $form
 */

// Scripts are loaded via an event on view.layout and can be managed in search-form-main-header.phtml.

$params = $this->params()->fromQuery() ?: [];
$form
    ->setData($params)
    ->prepare();
?>
<style>
    #form-search input[type="search"]{
        max-width: 95%;
    }
</style>

<div id="advanced-search-form-wrapper">
    <div id="advanced-search-form">
        <?= $this->form($form) ?>
    </div>
</div>

<script>
    $(document).ready(function(){
        $(".inputs").attr('class', 'inputs input-group flex-nowrap');
    });

</script>
