<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * @var array $sortOptions
 * @var ?\Laminas\Form\Element\Select $sortSelect
 * @var bool $asSortUrls
 * @var string $title
 */

if (empty($sortSelect)) return;
$sortSelect->setLabel('Sorteren op ');
?>

<div class="text-right search-sort<?= $asSortUrls ? ' search-sort-urls' : '' ?>">
    <?= $this->formLabel($sortSelect) ?>
    <?= $this->formSelect($sortSelect) ?>
</div>
