<?php
$assetUrl =$this->plugin('assetUrl');
$hyperlink = $this->plugin('hyperlink');
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$template = $item->resourceTemplate();
if($template):
    $type = $template->label();
else:
    $type = "";
endif;

$defaultThumbnail = $assetUrl('thumbnails/default.png', 'Omeka');

?>

<section class="section breadcrumb-section" style="padding-bottom:1rem;">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<?php echo $site->url();?>">Home</a></li>
        <li><a href=""></a><?php echo $type;?></li>
        <li><?php echo $item->displayTitle(); ?></li>
      </ul>
    </nav>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns">
        <?php if (!$embedMedia && $itemMedia): ?>
          <div class="column is-4">
            <div class="slideshow-show">
              <div class="slider-for">
                <?php foreach($itemMedia as $media):?>
                  <div class="has-text-centered">
                    <?php $url = str_replace('http:', '', $media->thumbnailUrl('large'));?>
                    <img src="<?php echo $url;?>">
                  </div>
                <?php endforeach;?>
              </div>
              <div class="slider-nav" role="toolbar">
                <?php foreach($itemMedia as $media):?>
                  <div class="">
                    <?php $url = str_replace('http:', '', $media->thumbnailUrl('medium'));?>
                    <img src="<?php echo $url;?>">
                  </div>
                <?php endforeach;?>
              </div>
            </div> 
          </div>
        <?php endif; ?>
        <?php $this->trigger('view.show.before'); ?>
        <?php if ($embedMedia && $itemMedia): ?>
          <div class="column is-4">
            <div class="media-embeds">
            <?php foreach ($itemMedia as $media):
                echo $media->render();
            endforeach;
            ?>
            </div>
          </div>
        <?php endif; ?>

        <div class="column">
          <h1 class="title is-3 is-family-secondary"><?php echo $item->displayTitle(); ?></h1>
          <?php if($type == "Collection focus"):?>            
          <h2 class="subtitle is-5 is-family-secondary">
            <?php echo $item->value("cw:colFocusStatus");?> collectiefocus van 
            <?php if($item->value("cw:isCurrentKeeperOfName")):?>
              of <a href=""><?php echo $item->value("cw:isCurrentKeeperOfName");?></a>
            <?endif; ?>  
          </h2>  
          <?php elseif($type):?>
          <h2 class="subtitle is-5 is-family-secondary">
            <?php echo $type; ?>
            <?php if($item->value("cw:isCurrentKeeperOfName")):?>
              of <a href=""><?php echo $item->value("cw:isCurrentKeeperOfName");?></a>
            <?endif; ?>  
          </h2>
          <?php endif;?>
          <?php if($item->value("cw:colType")):?>
          <div class="content">
            <?php foreach($item->value("cw:colType", ['all' => true]) as $val):?>
            <a class="button is-primary is-outlined is-small" href=""><?php echo $val->asHtml();?></a>  
            <?php endforeach;?>          
          </div>
          <?php endif;?>
          <div class="content">
            <div class="text">
            <?php echo $item->displayDescription();?>
            </div>
          </div>
          <div class="content">
          <span class="tag is-primary">idno: <?php echo $item->value("cw:idno");?></span>
          <span class="tag is-primary">Permalink</span>
          </div>
        </div>
      </div>
  </div>
</section>

<!-- Wat vind ik... -->
<section class="section">
  <div class="container">
  <div class="box">
    <h2 class="title is-4"><?php echo "Wat vind ik in de collectie?";?></h2>

    <?php if($item->value("cw:colDescription")):?>
      <div class="content">
        <div class="text">
        <?php echo $item->value("cw:colDescription"); ?>
        </div>
      </div>
    <?php endif;?>

    <div class="content">
      <h3 class="title is-4"><?php echo "Materialen";?></h3>
      <div class="columns">
        <div class="column is-3"> 
          <?php if($item->value("cw:colCreated")):?>
              <?php echo $item->value("cw:colCreated"); ?>
          <?php endif;?>
        </div>
        <div class="column is-3"> 
        <?php if($item->value("cw:colExtent")):?>
            <?php $extents = $item->value("cw:colExtent",['all' => true]); ?>
            <?php foreach($extents as $extent):?>
              <?php echo str_replace("$$",", ", $extent);?><br>
            <?php endforeach?>  
          <?php endif;?>
        </div>
        <div class="column is-3"> 
          <?php if($item->value("cw:describes")):?>
            <div class="text">
            <?php $decs = $item->value("cw:describes",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec_array[$dec->asHtml()] = "<a href=''>".$dec->asHtml()."</a>";?>            
            <?php endforeach?>  
            <?php ksort($dec_array);?>
            <?php echo implode("<br>",$dec_array); ?>
            </div>
          <?php endif;?>
        </div>
        <div class="column is-3"> 
          <?php if($item->value("cw:colLanguage")):?>
            <div class="text">
            <?php $decs = $item->value("cw:colLanguage",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec_array[$dec->asHtml()] = "<a href=''>".$dec->asHtml()."</a>";?>            
            <?php endforeach?>  
            <?php ksort($dec_array);?>
            <?php echo implode("<br>",$dec_array); ?>
            </div>
          <?php endif;?>
        </div>
      </div>
    </div>

    <div class="content">
      <h3 class="title is-4"><?php echo "Inhoud";?></h3>
      <div class="columns">
        <div class="column is-4"> 
        <?php if($item->value("cw:describes")):?>
          <div class="text">
            <?php $decs = $item->value("cw:describes",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec_array[$dec->asHtml()] = "<a href=''>".$dec->asHtml()."</a>";?>            
            <?php endforeach?>  
            <?php ksort($dec_array);?>
            <?php echo implode("<br>",$dec_array); ?>
            </div>
          <?php endif;?>
        </div>
        <div class="column is-4"> 
        <?php if($item->value("cw:describes")):?>
          <div class="text">
            <?php $decs = $item->value("cw:describes",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec_array[$dec->asHtml()] = "<a href=''>".$dec->asHtml()."</a>";?>            
            <?php endforeach?>  
            <?php ksort($dec_array);?>
            <?php echo implode("<br>",$dec_array); ?>
            </div>
          <?php endif;?>
        </div>
        <div class="column is-4"> 
          <?php if($item->value("cw:describes")):?>
            <div class="text">
            <?php $decs = $item->value("cw:describes",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec_array[$dec->asHtml()] = "<a href=''>".$dec->asHtml()."</a>";?>            
            <?php endforeach?>  
            <?php ksort($dec_array);?>
            <?php echo implode("<br>",$dec_array); ?>
            </div>
          <?php endif;?>
        </div>
      </div>
    </div>

    <div class="content">
      <?php if($item->value("cw:colHeritageRegister") == "Is a listed Flemish masterpiece"):?>
        <p>Deze collectie is erkend als topstuk door de Vlaamse overheid. Lees er meer over op de
          <a href="<?php echo $item->value("cw:isInscribedOnPrefix").$item->value("cw:isInscribedOnIdno")?>">topstukkendatabank</a></p>
      <?php endif;?>  
      <?php $notes = $item->value("cw:colNote",['all' => true]); ?>

      <?php foreach($notes as $note):?>
        <?php $note = explode("$$",$note);?>
        <?php if($note[1] == 'General'):?>          
          <?php echo $note[2];?><br>
        <?php endif;?>
      <?php endforeach?>  
    </div>     
        </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns">
    <div class="column is-3">
      <?php if($type == "Institution collection"):?>
        <?php $treeItem = $item;?>
      <?php elseif($item->value("cw:isPartOf")):?>
        <?php $treeItem = $item;?>
      <?php endif;?>  
        <div class="floating-nav">
          <div class="first"><a class="manuscript" href="<?php echo $treeItem->url(); ?>"><?php echo $treeItem->displayTitle();?></a></div>
          <?php 
          //find related collections
          $relCols = $treeItem->value("cw:isPartOfColFocus",['all' => true]);
          $relCols_a = [];$relCols_final;
          foreach($relCols as $relCol):
            $relCols_a[$relCol->asHtml()] = $relCol->asHtml();
          endforeach;
          ksort($relCols_a);
          foreach($relCols_a as $relCol):
            $query = "";
            parse_str("property[0][joiner]=and&property[0][property]=194&property[0][type]=eq&property[0][text]=".$relCol."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
            $rels = $this->api()->search('items',$query);
            $rels = $rels->getContent();
            if($rels):
              $relCols_final[] = $rels[0];
            endif;  
          endforeach;?>
          <?php if($relCols_final):?>
            <h3 class="title is-6" style="margin-bottom:0.5rem;">Collectiefocussen</h3>
            <ul>
              <?php foreach($relCols_final as $subcollection):?>                 
                <li>
                    <?= $hyperlink->raw($subcollection->displayTitle(), $subcollection->url(), ['class' => 'resource-link']) ?>
                </li>              
              <?php endforeach;?>
            </ul>
          <?php endif;?>     
          <?php
            //find sub-collections
            $query = "";
            parse_str("property[0][joiner]=and&property[0][property]=235&property[0][type]=eq&property[0][text]=".$item->value('cw:idno')."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
            $subcollections = $this->api()->search('items',$query);
            $subcollections = $subcollections->getContent();
          ?>
          <?php if($subcollections):?>
            <h3 class="title is-6" style="margin-bottom:0.5rem;margin-top:1.5rem;">Deelcollecties</h3>
            <ul>
            <?php foreach($subcollections as $subcollection):?>
              <?php if($item->displayTitle() ==  $subcollection->displayTitle()):?>
                <li style="font-weight:bold;">
              <?php else:?>
                <li>
              <?php endif;?>    
                    <?= $hyperlink->raw($subcollection->displayTitle(), $subcollection->url(), ['class' => 'resource-link']) ?>
              </li> 
            <?php endforeach;?>
            </ul>  
          <?php endif;?>  
        </div>
    </div>
      
    <div class="column is-9">
      <?php if($type == "Collection focus"):?>
      <section class="section">
        <div class="container">
        <div class="box">
          <h2 class="title is-4"><?php echo "Positionering";?></h2>
          <?php if($item->value("cw:colPositioning")):?>
              <p><?php echo $item->value("cw:colPositioning"); ?></p>
          <?php endif;?>  
            
          <?php if($item->value("cw:isCurrentCollaboratorName")):?>
            <h3 class="title is-5"><?php echo "Afstemmingspartners";?></h3>  
            <ul>
            <?php $texts = $item->value("cw:isCurrentCollaboratorName",['all' => true]); ?>
            <?php foreach($texts as $text):?>
              <li><?php echo $text;?></li>
            <?php endforeach;?>
            </ul> 
          <?php endif;?>

          <?php //if($item->value("cw:colDevGoalsArea")):?>
            <h3 class="title is-5"><?php echo "Bestaande collectieafspraken";?></h3>  
            <p>to do</p>
          <?php //endif;?>
          </div> 
        </div>       
      </section>
      <?php endif;?>

      <section class="section">
        <div class="container">
        <div class="box">
          <h2 class="title is-4"><?php echo "Zoeken in de collectie?";?></h2>
          <p>Deze collectie is voor <?php echo $item->value("cw:colItemsCataloguedOverall")?>% ontsloten. Via onlinecatalogie vind je <?php echo $item->value("cw:colItemsCataloguedOnline")?>% van de collectie terug.<p>
          <?php if($item->value("cw:colItemsCataloguedNote")):?>
              <p><?php echo $item->value("cw:colItemsCataloguedNote"); ?></p>
          <?php endif;?>  
          <p><a href="<?php echo $item->value("cw:isPrimaryCatalogueOfPrefix").$item->value("cw:isPrimaryCatalogueOfIdno")?>">Naar de catalogus</a> Zoektip: Filter in het zijmenu op 'organisatie' om enkel in deze collectie te zoeken.</p>
          
          <?php if($item->value("cw:isSupplementaryCatalogueOf")):?>
              <p>Je vindt de collectie ook terug in deze onlinecatalogie en -databanken:</p>
              <ul>
              <?php $odbs = $item->value("cw:isSupplementaryCatalogueOf",['all' => true]); ?>
              <?php foreach($odbs as $odb):?>
                <?php $odb = explode("$$",$odb);?>
                <li><a href="<?php echo $odb[2].$odb[0];?>"><?php echo $odb[1];?></a><li>
              <?php endforeach;?>
              </ul> 
          <?php endif;?>

          <p>Deze collectie staat beschreven in een gepubliceerde catalogus: to do</p>
          <p>Deze collectie staat beschreven in een ongepubliceerde catalogus: to do</p>

        </div>   </div>       
      </section>

<section class="section">
  <div class="container">
    <div class="box">
    <h2 class="title is-4"><?php echo "De collectie raadplegen?";?></h2>
    <h3 class="title is-5"><?php echo "Online";?></h3>
    <p>Op zoek naar digitale exemplaren van werken uit de collectie? to do</p>

    <h3 class="title is-5"><?php echo "Ter plekke";?></h3>
    <?php if($item->value("cw:isCurrentKeeperOfName")):?>
       <p> Wil je deze collectie ter plekke raadplegen, dan ke je terecht bij:</p>
        <ul>
        <?php $odbs = $item->value("cw:isCurrentKeeperOfName",['all' => true]); ?>
        <?php foreach($odbs as $odb):?>
          <li>
            <?php echo $odb;?><br>
            <a href="">Meer over de organisatie (intern)</a>  
          <li>
        <?php endforeach;?>
        </ul> 
    <?php endif;?>
    
    <div class="content">
    <?php foreach($notes as $note):?>
        <?php $note = explode("$$",$note);?>
        <?php if($note[1] == 'Consultation'):?>          
          <p><?php echo $note[2];?></p>
        <?php endif;?>
      <?php endforeach?>  

  </div>   </div>       
</section>

<section class="section">
  <div class="container">
    <div class="box">
    <h2 class="title is-4"><?php echo "Historiek van de collectie";?></h2>
    <?php if($item->value("cw:colProvenance")):?>
      <div class="content">
     
        <p>Deze collectie werd samengesteld in de periode <?php echo $item->value("cw:colDateContentCreated");?>.
        <div class="text">
        <?php echo $item->value("cw:colProvenance"); ?>
    </div>
      </div>
    <?php endif;?>


    <div class="content">
      <h3 class="title is-4"><?php echo "Actoren";?></h3>
      <div class="columns">
        <div class="column is-4"> 
          <h4 class="title is-5"><?php echo "Eigenaars";?></h4>
          <?php if($item->value("cw:isCurrentOwnerOf")):?>
            <?php $decs = $item->value("cw:isCurrentOwnerOf",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec_array[$dec->asHtml()] = $dec->asHtml();?>            
            <?php endforeach?>  
            <?php ksort($dec_array);?>
            <?php echo implode("<br>",$dec_array); ?>
          <?php endif;?>
        </div>
        <div class="column is-4"> 
          <h4 class="title is-5"><?php echo "Collectievormers";?></h4>
          <?php if($item->value("cw:isCurrentCuratorOf")):?>
            <?php $decs = $item->value("cw:isCurrentCuratorOf",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec_array[$dec->asHtml()] = $dec->asHtml();?>            
            <?php endforeach?>  
            <?php ksort($dec_array);?>
            <?php echo implode("<br>",$dec_array); ?>
          <?php endif;?>
        </div>
        <div class="column is-4"> 
          <h4 class="title is-5"><?php echo "Beheerders";?></h4>
          <?php if($item->value("cw:isCurrentKeeperOf")):?>
            <?php $decs = $item->value("cw:isCurrentKeeperOf",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec_array[$dec->asHtml()] = $dec->asHtml();?>            
            <?php endforeach?>  
            <?php ksort($dec_array);?>
            <?php echo implode("<br>",$dec_array); ?>
          <?php endif;?>
        </div>
      </div>
    </div>
            </div> 
</section>

<section class="section">
  <div class="container">
    <div class="box">
    <?php if($type == "Collection focus"):?>
      <h2 class="title is-4"><?php echo "Plannen rond de collectiefocus";?></h2>
    <?php else:?>
      <h2 class="title is-4"><?php echo "Plannen rond de collectie";?></h2>
    <?php endif;?>  
    
    <?php if($item->value("cw:colFormsPartOfCoreCollection") == "Yes"):?>
      <h3 class="title is-5">De collectie behoort tot de kerncollectie</h3>
    <?php endif;?>  
    <?php if($item->value("cw:colDevPolicyAbstract")):?>
      <div class="text">
      <p><?php echo $item->value("cw:colDevPolicyAbstract");?></p>
    </div>
    <?php endif;?>  
    <hr>
    <?php if($item->value("cw:colDevPlan")):?>
      <?php $plans = $item->value("cw:colDevPlan",['all' => true]); ?>
      <?php foreach($plans as $plan):?>
        <?php $plan = explode("$$",$plan);?>
        <p>Lees het collectiebeleidsplan: <a href="<?php echo $plan[3];?>"><?php echo $plan[2];?>, <?php echo $plan[0];?> - <?php echo $plan[1];?></a></p>
      <?php endforeach?>  
    <?php endif;?>  
    <hr>    
    <?php if($type == "Sub-collection" || $type == "Collection focus"):?>    
      <h3 class="title is-5"><?php echo "Acquisitiebeleid";?></h3>     
      <p>De acquisitiestatus van de collectie is <?php echo $item->value("cw:colAccrualPolicy");?></p> 
      <p>Deze collectie wordt <?php echo $item->value("cw:colAccrualPeriodicity");?> aangevuld door:</p>
      <?php $methods = $item->value("cw:colAccrualMethod",['all' => true]); ?>
      <ul>
      <?php foreach($methods as $method):?>
        <li><?php echo $method->asHtml();?></li>
      <?php endforeach;?>  
      </ul>
    <?php endif;?>
    <hr>    
    <?php if($type == "Collection focus"):?>    
      <h3 class="title is-5"><?php echo "Doelstellingen";?></h3>     
      <?php $texts = $item->value("cw:colDevGoals",['all' => true]); ?>
      
      <?php foreach($texts as $text):?>
        <?php $texte = eplode("$$",$text->asHtml());?>
        <h4 class="title is-6"><?php echo array_shift($texte);?></h4>
        <?php foreach($texte as $text):?>
          <p><?php echo $text;?></p>
        <?php endforeach;?>
      <?php endforeach;?>  
      
    <?php endif;?>
    </div>
  </div>       
</section>
<?php
//idno -> 192
//isPartOf -> 235

//find sub-collections
$query = "";
parse_str("property[0][joiner]=and&property[0][property]=235&property[0][type]=eq&property[0][text]=".$item->value('cw:idno')."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
$subcollections = $this->api()->search('items',$query);
$subcollections = $subcollections->getContent();?>

<?php if($subcollections):?>
<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Onderliggende collecties";?></h2>
      <div class="columns" style="overflow:auto;">
        <?php foreach($subcollections as $subcollection):?>
           <?php
           $media = $subcollection->primaryMedia();
           if($media):
            $url = str_replace('http:', '', $media->thumbnailUrl('square'));
           else: 
            $url = $defaultThumbnail;
           endif; 
           //$thumbnail = $media ? $thumbnailHelper($media, 'square') : $defaultThumbnail; 
           ?>      
           <div class="column is-2">
            <div class="">
              <a href="<?php echo $subcollection->url();?>"><img src="<?php echo $url;?>"></a>
            </div>   
            <div class="content resource-metadata-grid">
            <h5 class="title is-6" style="margin:1rem 0 0 0;"><a class="resource-link" href="<?php echo $subcollection->url();?>">
               <?php echo $subcollection->displayTitle();?>
              </a></h5>
            </div>
            <?php //echo $subcollection->displayTitle();?>
           </div>
        <?php endforeach;?>
      </div> 
    </div>
  </div>
</section>
<?php endif;?>

<?php 
//find related collections
$relCols = $item->value("cw:associatedCollection",['all' => true]);
$relCols_a = [];$relCols_final;
foreach($relCols as $relCol):
  $relCols_a[$relCol->asHtml()] = $relCol->asHtml();
endforeach;
ksort($relCols_a);
foreach($relCols_a as $relCol):
  $query = "";
  parse_str("property[0][joiner]=and&property[0][property]=194&property[0][type]=eq&property[0][text]=".$relCol."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
  $rels = $this->api()->search('items',$query);
  $rels = $rels->getContent();
  if($rels):
    $relCols_final[] = $rels[0];
  endif;  
endforeach;?>
<?php if($relCols_final):?>
<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Verwante collecties";?></h2>
      <div class="columns" style="overflow:auto;">
        <?php foreach($relCols_final as $subcollection):?>
           <?php
           $media = $subcollection->primaryMedia();
           if($media):
            $url = str_replace('http:', '', $media->thumbnailUrl('square'));
           else: 
            $url = $defaultThumbnail;
           endif; 
           ?>      
           <div class="column is-2">
            <div class="">
              <a href="<?php echo $subcollection->url();?>"><img src="<?php echo $url;?>"></a>
            </div>   
            <div class="content resource-metadata-grid">
            <h5 class="title is-6" style="margin:1rem 0 0 0;"><a class="resource-link" href="<?php echo $subcollection->url();?>">
               <?php echo $subcollection->displayTitle();?>
              </a></h5>
            </div>
            <?php //echo $subcollection->displayTitle();?>
           </div>
        <?php endforeach;?>
      </div> 
    </div>
  </div>
</section>
<?php endif;?>

<?php 
//find related collections
$relCols = $item->value("cw:isPartOfColFocus",['all' => true]);
$relCols_a = [];$relCols_final;
foreach($relCols as $relCol):
  $relCols_a[$relCol->asHtml()] = $relCol->asHtml();
endforeach;
ksort($relCols_a);
foreach($relCols_a as $relCol):
  $query = "";
  parse_str("property[0][joiner]=and&property[0][property]=194&property[0][type]=eq&property[0][text]=".$relCol."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
  $rels = $this->api()->search('items',$query);
  $rels = $rels->getContent();
  if($rels):
    $relCols_final[] = $rels[0];
  endif;  
endforeach;?>
<?php if($relCols_final):?>
<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "De collectie draagt bij tot deze collectiefocussen";?></h2>
      <div class="columns" style="overflow:auto;">
        <?php foreach($relCols_final as $subcollection):?>
           <?php
           $media = $subcollection->primaryMedia();
           if($media):
            $url = str_replace('http:', '', $media->thumbnailUrl('square'));
           else: 
            $url = $defaultThumbnail;
           endif; 
           ?>      
           <div class="column is-2">
            <div class="">
            <a href="<?php echo $subcollection->url();?>"><img src="<?php echo $url;?>"></a>
            </div>   
            <div class="content resource-metadata-grid">
            <h5 class="title is-6" style="margin:1rem 0 0 0;"><a class="resource-link" href="<?php echo $subcollection->url();?>">
               <?php echo $subcollection->displayTitle();?>
              </a></h5>
            </div>
            <?php //echo $subcollection->displayTitle();?>
           </div>
        <?php endforeach;?>
      </div> 
    </div>
  </div>
</section>
<?php endif;?>

<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Meer weten?";?></h2>     
      <?php if($item->value("cw:isAlsoDescribedBy")):?>
        <p>Je vindt meer over deze collectie op:</p>
        <?php $plans = $item->value("cw:isAlsoDescribedBy",['all' => true]); ?>
        <?php foreach($plans as $plan):?>
          <?php $plan = explode("$$",$plan);?>
          <li><a href="<?php echo $plan[2];?>"><?php echo $plan[1];?></a></li>
        <?php endforeach?>  
        <hr>   
      <?php endif;?>   
     
      
      <?php if($item->value("cw:refersTo")):?>
        <p>Of neem een kijkje in de volgende publicatie(s):</p>
        <?php $plans = $item->value("cw:refersTo",['all' => true]); ?>
        <?php foreach($plans as $plan):?>
          <?php $plan = explode("$$",$plan);?>
          <li><?php echo $plan[1];?> to do</li>
        <?php endforeach?>  
      <?php endif;?> 
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Vragen of feedback bij deze collectie?";?></h2>     
      <p>Heb je een vraag over deze collectie? <a href="">Stel ze aan de collectiebeheerder</a></p>
      <p>Heb je een aanvulling bij deze beschrijving? Merkte je foutieve of verouderde informatie op? <a href="">Laat het ons weten</a></p>
      <p>Deze beschrijving werd het laatst aangepast op ...</p>    
    </div>
  </div>
</section>

</div>

    </div>
  </div>                      
</section>
<?php

//find collections
$query = "";
parse_str("property[0][joiner]=and&property[0][property]=192&property[0][type]=eq&property[0][text]=".$item->value('cw:idno')."&resource_class_id[]=&resource_template_id[]=3&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
$containers = $this->api()->search('items',$query);
$containers = $containers->getContent();
?>
<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
<script>
  //
  if (location.hash) {
    
    var hash = $(location).attr('hash');
    window.location.hash = "";
    $(hash).find(".content").show();
        $(hash).addClass('open');
    
    setTimeout(function() { 
      var pos = $(hash).offset().top;
    $('body, html').animate({scrollTop: pos-66});
    window.location.hash = hash;
    }, 500);
  }
  $(document).ready(function(){
    $('.opener').click(function(e){
      e.preventDefault();
      $(this).parent().next(".content").toggle();
      $(this).parent().parent().toggleClass('open');
    });

    $('.floating-nav a').click(function(e){
      //e.preventDefault();
      
      var id = $(this).attr('href');      
      id = id.replace('#','');
      window.location.hash = id;
      var elem = document.getElementById(id);
     
      //elem.scrollIntoView(true);

      var pos = $($(this).attr('href')).offset().top;
      $('body, html').animate({scrollTop: pos - 66});
      
      $($(this).attr('href')).find(".content").show();
      $($(this).attr('href')).addClass('open');

    });

    $('.text').each(function(){
      if($(this).height() > 100){
        $(this).readmore({ speed: 75, collapsedHeight: 100, moreLink: '<a class="more-link" href="#">Read more</a>', lessLink: '<a class="more-link" href="#">Read less</a>' });;
      }      
    });
    
    

    $('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: false,
      fade: true,
      centerMode: true,
      asNavFor: '.slider-nav'
    });
    $('.slider-nav').slick({
      slidesToShow: 6,
      slidesToScroll: 1,
      asNavFor: '.slider-for',
      focusOnSelect: true
    });

    var quickLinks = document.querySelectorAll(".floating-nav a");
    var	positionArray =[], hashArray = [];

    for (var i=0; i<quickLinks.length; i++){
    	hashArray.push(quickLinks[i].href.substring(quickLinks[i].href.indexOf('#')+1));
    }

    for (var i=0; i<hashArray.length; i++){
    	positionArray.push(document.getElementById(hashArray[i]).getBoundingClientRect().top);
    }

    function isActive1(){
    	document.getElementsByClassName('is-active')[0];
    }

    document.addEventListener("scroll", scrollHandler, true);

    function scrollHandler() {
    	currentScrollPosition = document.documentElement.scrollTop;
    	//currentActivePosition = document.getElementsByClassName('is-active')[0].getBoundingClientRect().top;
    	for (var i=1; i<=positionArray.length; i++){
    		if (currentScrollPosition>=positionArray[i-1] && currentScrollPosition < positionArray[i]) {
    			var currentActive = document.getElementsByClassName('is-active')[0];
    				if (currentActive != undefined){
        			currentActive.classList.remove('is-active');
        		}
	        quickLinks[i-1].classList.add('is-active');
  			  break;
  		  }

    		if (currentScrollPosition>positionArray[positionArray.length-1]){
    			var currentActive = document.getElementsByClassName('is-active');
  				var currentActive = document.getElementsByClassName('is-active')[0];
  				if (currentActive != undefined){
      			currentActive.classList.remove('is-active');
    			}
    			quickLinks[quickLinks.length-1].classList.add('is-active');
    			break;
  		 }
  	  }
    };

    for (var i=0; i<quickLinks.length; i++){
    	quickLinks[i].addEventListener('click', function(event){
    		document.removeEventListener('scroll', scrollHandler, true);

    		/**
    		for (var j=0; j<quickLinks.length; j++){
    			if (quickLinks[j].classList.contains('is-active')){
    				quickLinks[j].classList.remove('is-active');
    			}
    		}
    		**/

    		isActive = document.getElementsByClassName('is-active')[0];

    		if (isActive != undefined){
    			isActive.classList.remove('is-active');
    		}

    		this.classList.add('is-active');
    		setTimeout(function(){
        			document.addEventListener("scroll", scrollHandler, true);
    	}, 600);
    	});
    }
  });
</script>
