<?php
$translate = $this->plugin('translate');
?>
<section class="section carousel-section" style="background:#2f2828;">
  <div class="container">
    <?php if ($this->heading): ?>
      <h2 class="title is-4 is-family-secondary"><?php echo $this->heading; ?></h2>
    <?php endif; ?>

    <?php if($block->dataValue('text')):?>
      <div class="content">
              <?php echo $block->dataValue('text');?>
      </div>
    <?php endif; ?>

    <?php if($this->resources):?>
    <div class="slider">
      <?php
      $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
      $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');

      foreach ($this->resources as $resource):
        $heading = $resource->value($headingTerm, ['default' => $translate('[Untitled]')]);
        $body = $resource->value('dcterms:description');
        if($resourceType == 'item-set'):
          $body = $resource->value('dcterms:description');
        endif;
        $type = $resource->resourceTemplate();
        if($type):
          $type= $type->label();
        elseif($resourceType == 'item-set'):
          $type= 'Collection';
        else:
          $type= "Object";
        endif;
      ?>
      <div class="slide">
            <?php
              $mediaurl = "";
              $media = $resource->media();
              
              $url = $resource->url();
            ?>

            <div class="slide-container">
              <a href="<?php echo $url;?>">              
              <div>
                <?php echo $media[0]->render();?>
                <img src="">
              </div>
              <div class="slide-content">
                
                <h5 class="title is-6 is-family-secondary">
                    <?php echo $resource->value('dcterms:title');?>
                </h5>
              
                <div class="content">
                  <?php $body = $resource->value('dcterms:description');?>
                  <?php if ($body): ?>
                    <?php
                      if(strlen($body) > 200):
                        $body = substr($body, 0, 200);
                        $body = substr($body, 0, strrpos($body, ' ')).' ...';
                      endif;
                    ?>
                    <p>
                      <?php echo $body; ?>
                    </p>
                  <?php endif; ?>
                </div>
              </div>
            </a>
          </div>
        </div>
      <?php endforeach; ?>
     
      </div>
    <?php if ($this->linkText):?>
      <div class="browse-all has-text-right">
        <?php if($this->linkText == 'All collections'):?>
          <a href="<?php echo $block->page()->site()->url().'/item-set';?>" class="button is-white">
            <?php echo $this->linkText;?>
          </a>
        <?php else:?>
          <a class="button is-outlined is-primary" href="<?php echo $block->page()->site()->url().'/page/'.strtolower($type);?>">
            <?php echo $this->linkText;?>
          </a>
        <?php endif;?>
      </div>
    <?php endif;?>
    <?php endif;?>
  </div>
</section>
<script>
  $( document ).ready(function() {
    $(".slider").slick({
      centerMode: true,
      centerPadding: '0px',
      slidesToShow: 5,
      responsive: [
        {
          breakpoint: 768,
          settings: {
            arrows: true,
            centerMode: true,
            centerPadding: '40px',
            slidesToShow: 3
          }
        },
        {
          breakpoint: 480,
          settings: {
            arrows: false,
            centerMode: true,
            centerPadding: '40px',
            slidesToShow: 1
          }
        }
      ]
    });  
  });  
</script>  
