<?php
$assetUrl =$this->plugin('assetUrl');
$hyperlink = $this->plugin('hyperlink');
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$template = $item->resourceTemplate();
if($template):
    $type = $template->label();
else:
    $type = "";
endif;

$defaultThumbnail = $assetUrl('thumbnails/default.png', 'Omeka');

?>

<section class="section breadcrumb-section" style="padding-bottom:1rem;">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<?php echo $site->url();?>">Home</a></li>
        <li><a href="<?php echo $site->url()."/search?facet[resource_template_id][]=".$type;?>"><?php echo $type;?></a></li>
        <li><?php echo $item->displayTitle(); ?></li>
      </ul>
    </nav>
  </div>
</section>
<?php if($type != 'Organisation' && $type != 'Publication'):?>
<section class="section">
  <div class="container">
    <div class="columns">
        <?php if ($itemMedia): ?>
          <?php
            $captions = []; $rights = [];$i=0;
            if($item->value("cw:collIllustration")):?>
                <?php foreach($item->value("cw:collIllustration", ['all' => true]) as $val):?>
                  
                  <?php $foto = explode("$$",$val->asHtml());?>
                  <?php if(isset($foto[2])):?>
                    <?php $captions[$i] = $foto[2]; ?>
                  <?php else:?>
                    <?php $captions[$i] = '' ?>
                  <?php endif;?>
                  <?php if(isset($foto[3])):?>
                    <?php $rights[$i] = $foto[3]; ?>
                  <?php else:?>
                    <?php $rights[$i] = '' ?>
                  <?php endif;?>
                  <?php $i++;?>
                <?php endforeach;?>    
           <?php endif;?>
         
          <div class="column is-4">
            <div class="slideshow-show">
              <div class="slider-for">
                <?php $i = 0;?>
                <?php foreach($itemMedia as $media):?>
                  <div>
                    <?php $url = str_replace('http:', '', $media->thumbnailUrl('large'));?>
                    <img src="<?php echo $url;?>">
                    <?php if($captions[$i] || $rights[$i]):?>
                    <div style="margin-top:0.5rem;margin-left:0.5rem;font-size:0.9rem;">
                      <?php if($captions[$i]):?>
                        <?php echo $captions[$i];?>
                      <?php endif;?>
                      <?php if($rights[$i]):?>
                        <br>
                        <span style="font-style:italic;"?>
                        <?php echo "Alle rechten voorbehouden: ".$rights[$i];?></span>
                      <?php endif;?>
                    </div>
                    <?php endif;?>
                    <?php $i++;?>
                  </div>
                <?php endforeach;?>
              </div>
              <?php if(sizeof($itemMedia) > 1):?>
              <div class="slider-nav" role="toolbar">
                <?php foreach($itemMedia as $media):?>
                  <div class="">
                    <?php $url = str_replace('http:', '', $media->thumbnailUrl('medium'));?>
                    <img src="<?php echo $url;?>">
                  </div>
                <?php endforeach;?>
              </div>
              <?php endif;?>
            </div> 
          </div>
        <?php endif; ?>
        <?php $this->trigger('view.show.before'); ?>
      

        <div class="column">
          <h1 class="title is-3 is-family-secondary">
            <?php echo $item->displayTitle(); ?>
            <?php if($item->value("cw:colDevPlanFile")):?>
              <a href="<?php echo $item->value("cw:colDevPlanFile");?>" class="button"><span class="icon is-small">
      <i class="fas fa-file-pdf"></i>
    </span></a>
            <?php endif;?>  
          </h1>
          <?php if($type == "Collection focus"):?>            
          <h2 class="subtitle is-5 is-family-secondary">
            <?php echo $item->value("cw:colFocusStatus");?> collectiefocus van 
            <?php if($item->value("cw:isCurrentKeeperOfName")):?>
              of <a href=""><?php echo $item->value("cw:isCurrentKeeperOfName");?></a>
            <?endif; ?>  
          </h2>  
          <?php elseif($type):?>
          <h2 class="subtitle is-5 is-family-secondary">
            <?php echo $type; ?>
            <?php if($item->value("cw:isCurrentKeeperOfName") && $item->value("cw:isCurrentKeeperOfIdno")):?>
              <?php
                $query = "";
                parse_str("property[0][joiner]=and&property[0][joiner]=and&property[0][property]=192&property[0][type]=eq&property[0][text]=".$item->value("cw:isCurrentKeeperOfIdno"),$query);
                $res = $this->api()->search('items',$query);
                $res = $res->getContent();
              ?>
              <?php if(isset($res[0])):?>
              of <a href="<?php echo $res[0]->url(); ?>"><?php echo $res[0]->displayTitle();?></a>
              <?php endif;?>       
            <?endif; ?>  
          </h2>
          <?php endif;?>
          <?php if($item->value("cw:colType")):?>
            <div class="content">
              <?php foreach($item->value("cw:colType", ['all' => true]) as $val):?>
                <a class="button is-primary is-outlined is-small" href="<?php echo $site->url()."/search?facet[cw%3AcolType][]=".$val->asHtml(); ?>"><?php echo $val->asHtml();?></a>  
              <?php endforeach;?>          
            </div>
          <?php endif;?>
          <div class="content">
            <div class="text">
            <?php echo $item->displayDescription();?>
            </div>
          </div>
          <div class="content">
          <span class="tag is-primary">idno: <?php echo $item->value("cw:idno");?></span>
          <span class="tag is-primary">Permalink</span>
          </div>
        </div>
      </div>
  </div>
</section>


<?php $relCols_final= array();?>
<section class="section">
  <div class="container">
    <div class="columns">
    <div class="column is-3">
      <?php $treeItem = $item;?>
      <?php if($type != "Institution collection"):?>      
        <?php
            //find parent
           $query = "";
           $parents = $item->value("cw:isPartOf",['all' => true]);
           
           foreach($parents as $parent):     
            if($parent->asHtml() != $item->value('cw:idno')):      
              parse_str("property[0][joiner]=and&property[0][property]=192&property[0][type]=eq&property[0][text]=".$parent->asHtml()."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
              $parent = $this->api()->searchOne('items',$query);
              $parent = $parent->getContent();
              if($parent->value('cw:collectionType') == "Institution collection"):               
                $treeItem = $parent;   
              else:
                //find parent
                $query = "";
                $parents = $item->value("cw:isPartOf",['all' => true]);
                
                foreach($parents as $parent):     
                  if($parent->asHtml() != $item->value('cw:idno')):      
                    parse_str("property[0][joiner]=and&property[0][property]=192&property[0][type]=eq&property[0][text]=".$parent->asHtml()."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
                    $parent = $this->api()->searchOne('items',$query);
                    $parent = $parent->getContent();
                    if($parent->value('cw:collectionType') == "Institution collection"):               
                      $treeItem = $parent;
                    endif;
                 endif;
                endforeach;               
              endif;
            endif;
           endforeach;
        ?>
      <?php endif;?>  
        <div class="floating-nav">
          <div class="first">
            <?php if($treeItem->displayTitle() == $item->displayTitle()):?>                   
              <a class="manuscript" style="font-weight:bold;" href="<?php echo $treeItem->url(); ?>">
                <?php echo $treeItem->displayTitle();?>
              </a>
            <?php else:?>
              <a class="manuscript" href="<?php echo $treeItem->url(); ?>">
                <?php echo $treeItem->displayTitle();?>
              </a>  
            <?php endif;?>  
          </div>
          <?php 
          //find related collections
          $relCols = $treeItem->value("cw:isPartOfColFocus",['all' => true]);
          $relCols_a = [];$relCols_final;
          foreach($relCols as $relCol):
            $relCols_a[$relCol->asHtml()] = $relCol->asHtml();
          endforeach;
          ksort($relCols_a);
          foreach($relCols_a as $relCol):
            $query = "";
            parse_str("property[0][joiner]=and&property[0][property]=194&property[0][type]=eq&property[0][text]=".$relCol."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
            $rels = $this->api()->search('items',$query);
            $rels = $rels->getContent();
            if($rels):
              $relCols_final[] = $rels[0];
            endif;  
          endforeach;?>
          <?php if($relCols_final):?>
            <h3 class="title is-6" style="margin-bottom:0.5rem;">Collectiefocussen</h3>
            <ul>
              <?php foreach($relCols_final as $subcollection):?>                 
                <li>
                    <?= $hyperlink->raw($subcollection->displayTitle(), $subcollection->url(), ['class' => 'resource-link']) ?>
                </li>              
              <?php endforeach;?>
            </ul>
          <?php endif;?>     
          <?php
            //find sub-collections
            //192 = idno
            //235 = partOf
            $relCols = $treeItem->value("cw:isPartOf",['all' => true]);
            $relCols_a = [];$subcollections = [];
            foreach($relCols as $relCol):              
              $relCols_a[$relCol->asHtml()] = $relCol->asHtml();
            endforeach;
            ksort($relCols_a);
            $query = "";
            parse_str("property[0][joiner]=and&property[0][property]=235&property[0][type]=eq&property[0][text]=".$treeItem->value('cw:idno')."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
            $rels = $this->api()->search('items',$query);
            $rels = $rels->getContent();
            foreach($rels as $rel):
              $subcollections[] = $rel;
            endforeach;?>
          <?php if($subcollections):?>
            <h3 class="title is-6" style="margin-bottom:0.5rem;margin-top:1.5rem;">Deelcollecties</h3>
            <ul>
            <?php foreach($subcollections as $subcollection):?>
              <?php if($treeItem->displayTitle() !=  $subcollection->displayTitle()):?>                
                <?php if($item->displayTitle() == $subcollection->displayTitle()):?>
                  <li style="font-weight:bold;">
                <?php else:?>    
                  <li>
                <?php endif;?>             
                    <?= $hyperlink->raw($subcollection->displayTitle(), $subcollection->url(), ['class' => 'resource-link']) ?>
                </li>               
              <?php
                $query = "";
                parse_str("property[0][joiner]=and&property[0][property]=235&property[0][type]=eq&property[0][text]=".$subcollection->value('cw:idno')."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
                $subrels = $this->api()->search('items',$query);
                $subrels = $subrels->getContent();
                if($subrels):
                  echo '<ul style="margin-left:1.5rem;">';
                  foreach($subrels as $subrel):
                    if($subcollection->displayTitle() != $subrel->displayTitle()):?>
                    <?php $subsubcollections[] = $subrel;?>
                      <?php if($item->displayTitle() == $subrel->displayTitle()):?>
                        <li style="font-weight:bold;">
                      <?php else:?>    
                        <li>
                      <?php endif;?>  
                        <?= $hyperlink->raw($subrel->displayTitle(), $subrel->url(), ['class' => 'resource-link']) ?>
                      </li> 
                      <?php
                        $query = "";
                        parse_str("property[0][joiner]=and&property[0][property]=235&property[0][type]=eq&property[0][text]=".$subrel->value('cw:idno')."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
                        $subrels2 = $this->api()->search('items',$query);
                        $subrels2 = $subrels2->getContent();
                        if($subrels2):
                          echo '<ul style="margin-left:1.5rem;">';
                          foreach($subrels2 as $subrel2):
                            if($subrel->displayTitle() != $subrel2->displayTitle()):?>
                              <?php if($item->displayTitle() == $subrel2->displayTitle()):?>
                                <li style="font-weight:bold;">
                              <?php else:?>    
                                <li>
                              <?php endif;?>  
                                <?= $hyperlink->raw($subrel2->displayTitle(), $subrel2->url(), ['class' => 'resource-link']) ?>
                              </li> 
                            <?php endif;?>
                          <?php endforeach;
                          echo '</ul>';
                        endif;
                      ?>
                    <?php endif;?>
                  <?php endforeach;
                  echo '</ul>';
                endif;
              ?>
              <?php endif;?>    
            <?php endforeach;?>
            </ul>  
          <?php endif;?>  
        </div>
    </div>
      
    <div class="column is-9">
      <!-- Wat vind ik... -->
      <section class="section">
        <div class="container">
        <div class="box">
          <h2 class="title is-4"><?php echo "Wat vind ik in de collectie?";?></h2>

          <?php if($item->value("cw:colDescription")):?>
            <div class="content">
              <div class="text">
              <?php echo $item->value("cw:colDescription"); ?>
              </div>
            </div>
          <?php endif;?>

          <?php if($item->value("cw:describes")):?>
              <?php $decs = $item->value("cw:describes",['all' => true]); ?>
              <?php $dec_array = [];?>
              <?php foreach($decs as $dec):?>
                  <?php $full = $dec->asHtml();?>
                  <?php $dec = explode('$$', $dec->asHtml());?>         
                  <?php if(isset($dec[2])):?>  
                    <?php $dec_array[$dec[0]][] = array('name' => $dec[2], 'full' => $full);?>            
                  <?php endif;?>
              <?php endforeach?>  
          <?php endif;?>

          <div class="content tagblock">
            <h3 class="title is-4"><?php echo "Materialen";?></h3>
            <div class="columns">
              <div class="column is-3"> 
              
                <?php if($item->value("cw:colCreated")):?>
                  <ul class="text">
                    <?php $extents = $item->value("cw:colCreated",['all' => true]); ?>
                    <?php foreach($extents as $extent):?>                
                      <li>
                        <?php echo str_replace("$$",", ", $extent);?>
                      </li>
                    <?php endforeach?>  
                  </ul>  
                <?php endif;?>    
              </div>
              <div class="column is-3"> 
                <?php if($item->value("cw:colExtent")):?>
                  <ul class="text">
                    <?php $extents = $item->value("cw:colExtent",['all' => true]); ?>
                    <?php foreach($extents as $extent):?>
                      <?php $extent = explode('$$',$extent);?>
                      <li>
                        <?php echo ($extent[4] != 'Exact') ? 'ca. ' : ''; ?>
                        <?php echo ($extent[2]) ? $extent[2] : ''; ?>
                        <?php echo ($extent[3]) ? ' '.$extent[3] : ''; ?>
                        <?php echo ($extent[0]) ? ' '.$extent[0] : ''; ?>
                        <?php echo ($extent[1]) ? ', '.$extent[1] : ''; ?>
                        <?php echo ($extent[4] != 'Exact') ? ' ('.$extent[4].')' : ''; ?>
                      </li>
                    <?php endforeach?>  
                  </ul>  
                <?php endif;?>         
              </div>
              <div class="column is-3"> 
                <?php if(isset($dec_array['Publicatietype'])):?>
                  <ul class="text">
                  <?php asort($dec_array['Publicatietype']);?>
                  <?php foreach($dec_array['Publicatietype'] as $dec):?>           
                    <li><a href='<?php echo $site->url()."/search?facet[cw%3Adescribes][]=".$dec['full']; ?>'><?php echo $dec['name'];?></a></li>            
                  <?php endforeach?>
                  </ul>
                <?php endif;?>
              </div>
              <div class="column is-3"> 
                <?php if($item->value("cw:colLanguage")):?>
                  <ul class="text">
                  <?php $talen = $item->value("cw:colLanguage",['all' => true]); ?>
                  <?php $taal_array = [];?>
                  <?php foreach($talen as $taal):?>
                    <?php $taal_array[$taal->asHtml()] = $taal->asHtml();?>            
                  <?php endforeach?>  
                  <?php ksort($taal_array);?>
                  <?php foreach($taal_array as $taal):?>   
                    <?php $taal = explode('$$',$taal);?>        
                    <li><a href='<?php echo $site->url()."/search?facet[cw%3AcolLanguageName][]=".$taal[0]; ?>'><?php echo $taal[0];?></a></li>            
                  <?php endforeach?>
                  </ul>
                <?php endif;?>
              </div>
            </div>
          </div>

          <div class="content tagblock">
            <h3 class="title is-4"><?php echo "Inhoud";?></h3>
            <div class="columns">
              <div class="column is-4"> 
                <?php if(isset($dec_array['Onderwerp'])):?>
                  <h5 class="title is-6"><?php echo "Over het onderwerp";?></h5>
                  <ul class="text">
                  <?php asort($dec_array['Onderwerp']);?>
                  <?php foreach($dec_array['Onderwerp'] as $dec):?>           
                    <li><a href='<?php echo $site->url()."/search?facet[cw%3Adescribes][]=".$dec['full']; ?>'><?php echo $dec['name'];?></a></li>            
                  <?php endforeach?>
                  </ul>
                <?php endif;?>
            
              </div>
              <div class="column is-4"> 
                <?php if(isset($dec_array['Regio'])):?>
                  <h5 class="title is-6"><?php echo "Over de regio";?></h5>
                  <ul class="text">
                  <?php asort($dec_array['Regio']);?>
                  <?php foreach($dec_array['Regio'] as $dec):?>           
                    <li><a href='<?php echo $site->url()."/search?facet[cw%3Adescribes][]=".$dec['full']; ?>'><?php echo $dec['name'];?></a></li>            
                  <?php endforeach?>
                  </ul>
                <?php endif;?>
              </div>
              <div class="column is-4"> 
                <?php if(isset($dec_array['Periode'])):?>
                  <h5 class="title is-6"><?php echo "Over de periode";?></h5>
                  <ul class="text">
                  <?php asort($dec_array['Periode']);?>
                  <?php foreach($dec_array['Periode'] as $dec):?>           
                    <li><a href='<?php echo $site->url()."/search?facet[cw%3Adescribes][]=".$dec['full']; ?>'><?php echo $dec['name'];?></a></li>            
                  <?php endforeach?>
                  </ul>
                <?php endif;?>
              </div>
            </div>
          </div>

          <div class="content">
            <?php if($item->value("cw:colHeritageRegister") == "Is a listed Flemish masterpiece"):?>
              <p>Deze collectie is erkend als topstuk door de Vlaamse overheid. Lees er meer over op de
                <a href="<?php echo $item->value("cw:isInscribedOnPrefix").$item->value("cw:isInscribedOnIdno")?>">topstukkendatabank</a>.</p>
            <?php endif;?>  
            <?php $notes = $item->value("cw:colNote",['all' => true]); ?>

            <?php foreach($notes as $note):?>
              <?php $note = explode("$$",$note);?>
              <?php if($note[1] == 'General'):?>          
                <?php echo $note[2];?><br>
              <?php endif;?>
            <?php endforeach?>  
          </div>     
        </div>
      </section>

      <?php if($type == "Collection focus"):?>
      <section class="section">
        <div class="container">
        <div class="box">
          <h2 class="title is-4"><?php echo "Positionering";?></h2>
          <?php if($item->value("cw:colPositioning")):?>
              <p><?php echo $item->value("cw:colPositioning"); ?></p>
          <?php endif;?>  
            
          <?php if($item->value("cw:isCurrentCollaboratorName")):?>
            <h3 class="title is-5"><?php echo "Afstemmingspartners";?></h3>  
            <ul>
            <?php $texts = $item->value("cw:isCurrentCollaboratorName",['all' => true]); ?>
            <?php foreach($texts as $text):?>
              <li><?php echo $text;?></li>
            <?php endforeach;?>
            </ul> 
          <?php endif;?>

          <?php //if($item->value("cw:colDevGoalsArea")):?>
            <h3 class="title is-5"><?php echo "Bestaande collectieafspraken";?></h3>  
            <p>to do</p>
          <?php //endif;?>
          </div> 
        </div>       
      </section>
      <?php endif;?>

      <section class="section">
        <div class="container">
        <div class="box content">

          <h2 class="title is-4"><?php echo "Zoeken in de collectie?";?></h2>
          <p>Deze collectie is voor <?php echo $item->value("cw:colItemsCataloguedOverall")?>% ontsloten. Via onlinecatalogie vind je <?php echo $item->value("cw:colItemsCataloguedOnline")?>% van de collectie terug.<p>
          <?php if($item->value("cw:colItemsCataloguedNote")):?>
              <p><?php echo $item->value("cw:colItemsCataloguedNote"); ?></p>
          <?php endif;?>  
          <p><a class="button is-primary is-small" href="<?php echo $item->value("cw:isPrimaryCatalogueOfPrefix").$item->value("cw:isPrimaryCatalogueOfIdno")?>">Naar de catalogus</a>
          <span style="font-size:0.9rem">Zoektip: Filter in het zijmenu op 'organisatie' om enkel in deze collectie te zoeken.</span></p>
          
          <?php if($item->value("cw:isSupplementaryCatalogueOf")):?>
              <p>Je vindt de collectie ook terug in deze onlinecatalogie en -databanken:</p>
              <ul>
              <?php $odbs = $item->value("cw:isSupplementaryCatalogueOf",['all' => true]); ?>
              <?php foreach($odbs as $odb):?>
                <?php $odb = explode("$$",$odb);?>
                <li><a href="<?php echo $odb[2].$odb[0];?>"><?php echo $odb[1];?></a></li>
              <?php endforeach;?>
              </ul> 
          <?php endif;?>

          <?php if($item->value("cw:isPublishedCatalogueOf")):?>
            <p>Deze collectie staat beschreven in een gepubliceerde catalogus:</p>
              <ul>
              <?php $odbs = $item->value("cw:isPublishedCatalogueOf",['all' => true]); ?>
              <?php foreach($odbs as $odb):?>
                <?php $odb = explode("$$",$odb);?>
                <li>
                  <?php echo $odb[1];?> 
                  <?php if($item->value("cw:relBiblioRefItemSubject")):?>
                    (<?php echo $item->value("cw:relBiblioRefItemSubject");?>)
                  <?php endif;?>  
                </li>
              <?php endforeach;?>
              </ul> 
          <?php endif;?>

          <?php if($item->value("cw:colCatalogueUnpublished")):?>
            <p>Deze collectie staat beschreven in een ongepubliceerde catalogus:</p>
              <ul>
              <?php $odbs = $item->value("cw:colCatalogueUnpublished",['all' => true]); ?>
              <?php foreach($odbs as $odb):?>
                <?php $odb = explode("$$",$odb);?>
                <li><a href="<?php echo $odb[2];?>"><?php echo $odb[0];?> (<?php echo $odb[1];?>)</a></li>
              <?php endforeach;?>
              </ul> 
          <?php endif;?>

          

        </div>   </div>       
      </section>

<section class="section">
  <div class="container">
    <div class="box content">
    <h2 class="title is-4"><?php echo "De collectie raadplegen?";?></h2>
    <h3 class="title is-6"><?php echo "Online";?></h3>
    <p>Op zoek naar digitale exemplaren van werken uit de collectie? to do</p>

    <h3 class="title is-6"><?php echo "Ter plekke";?></h3>
    <?php if($item->value("cw:isCurrentKeeperOfName")):?>
       <p> Wil je deze collectie ter plekke raadplegen, dan kan je terecht bij:</p>
        
        <?php $odbs = $item->value("cw:isCurrentKeeperOfName",['all' => true]); ?>
        <?php foreach($odbs as $odb):?>          
            <strong><?php echo $odb;?></strong><br>
            <?php if($item->value("cw:isCurrentKeeperOfName") && $item->value("cw:isCurrentKeeperOfIdno")):?>
              <?php
                $query = "";
                parse_str("property[0][joiner]=and&property[0][joiner]=and&property[0][property]=192&property[0][type]=eq&property[0][text]=".$item->value("cw:isCurrentKeeperOfIdno"),$query);
                $res = $this->api()->search('items',$query);
                $res = $res->getContent();
              ?>
              <?php if(isset($res[0])):?>
                  <p class="is-size-6">
                    <?php echo $res[0]->value('cw:addressStreet')." ".$res[0]->value('cw:addressNumber')." ".$res[0]->value('cw:addressMailbox');?><br>
                    <?php echo $res[0]->value('cw:addressPostalCode').", ".$res[0]->value('cw:addressTown');?>
                  
                <br><a href="<?php echo $res[0]->url(); ?>">Meer over de organisatie</a>
                </p>
              <?php endif;?>       
            <?endif; ?>       
        <?php endforeach;?>
    <?php endif;?>
    
    <div class="content">
    <?php foreach($notes as $note):?>
        <?php $note = explode("$$",$note);?>
        <?php if($note[1] == 'Consultation'):?>          
          <p><?php echo $note[2];?></p>
        <?php endif;?>
      <?php endforeach?>  

  </div>   </div>       
</section>

<section class="section">
  <div class="container">
    <div class="box content">
    <h2 class="title is-4"><?php echo "Historiek van de collectie";?></h2>
    <?php if($item->value("cw:colProvenance")):?>
      <div class="content">     
        <p>Deze collectie werd samengesteld in de periode <?php echo $item->value("cw:colDateContentCreated");?>.
        <div class="text">
          <?php $text = $item->value("cw:colProvenance");?>
          <?php $text = str_replace('NL:','',$text);?>
          <?php echo $text; ?>
        </div>
      </div>
    <?php endif;?>


    <div class="content tagblock">
      <h3 class="title is-4"><?php echo "Actoren";?></h3>
      <div class="columns">            
          <?php if($item->value("cw:isCurrentOwnerOf")):?>
            <div class="column is-4">       
            <h5 class="title is-6"><?php echo "Eigenaars";?></h5>
            <?php $decs = $item->value("cw:isCurrentOwnerOf",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec = explode('$$', $dec->asHtml());?>
              <?php $dec_array[$dec[2]] = $dec[1];?>            
            <?php endforeach?>  
            <?php krsort($dec_array);?>
            <?php foreach($dec_array as $date=>$dec):?>
              <?php if($date):?>
                <span style="min-width:110px;display:inline-block;"><?php echo $date;?></span>
              <?php endif;?>
              <?php echo $dec;?><br>
            <?php endforeach?>  
            </div>
          <?php endif;?>        
           
          <?php if($item->value("cw:isCurrentCuratorOf")):?>
            <div class="column is-4">        
            <h5 class="title is-6"><?php echo "Collectievormers";?></h5>
            <?php $decs = $item->value("cw:isCurrentCuratorOf",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec = explode('$$', $dec->asHtml());?>
              <?php $dec_array[$dec[2]] = $dec[1];?>            
            <?php endforeach?>  
            <?php krsort($dec_array);?>            
            <?php foreach($dec_array as $date=>$dec):?>
              <?php if($date):?>
                <span style="min-width:110px;display:inline-block;"><?php echo $date;?></span>
              <?php endif;?>
              <?php echo $dec;?><br>
            <?php endforeach?>   
            </div>           
          <?php endif;?>        
              
          <?php if($item->value("cw:isCurrentKeeperOf")):?>
            <div class="column is-4">    
            <h5 class="title is-6"><?php echo "Beheerders";?></h5>
            <?php $decs = $item->value("cw:isCurrentKeeperOf",['all' => true]); ?>
            <?php $dec_array = [];?>
            <?php foreach($decs as $dec):?>
              <?php $dec = explode('$$', $dec->asHtml());?>
              <?php $dec_array[$dec[2]] = $dec[1];?>            
            <?php endforeach?>  
            <?php krsort($dec_array);?>
            <?php foreach($dec_array as $date=>$dec):?>
              <?php if($date):?>
                <span style="min-width:110px;display:inline-block;"><?php echo $date;?></span>
              <?php endif;?>
              <?php echo $dec;?><br>
            <?php endforeach?>  
            </div>
          <?php endif;?>        
      </div>
    </div>
            </div> 
</section>

<section class="section">
  <div class="container">
    <div class="box content">
    <?php if($type == "Collection focus"):?>
      <h2 class="title is-4"><?php echo "Plannen rond de collectiefocus";?></h2>
    <?php else:?>
      <h2 class="title is-4"><?php echo "Plannen rond de collectie";?></h2>
    <?php endif;?>  
    
    <?php if($item->value("cw:colFormsPartOfCoreCollection") == "Yes"):?>
      <h3 class="title is-5">De collectie behoort tot de kerncollectie</h3>
    <?php endif;?>  
    <?php if($item->value("cw:colDevPolicyAbstract")):?>
      <div class="text">
          <?php $text = $item->value("cw:colDevPolicyAbstract");?>
          <?php $text = str_replace('NL:','',$text);?>
          <?php echo $text; ?>
      </div>
    <?php endif;?>  
    <hr>
    <?php if($item->value("cw:colDevPlan")):?>
      <?php $plans = $item->value("cw:colDevPlan",['all' => true]); ?>
      <?php foreach($plans as $plan):?>
        <?php $plan = explode("$$",$plan);?>
        <p>Lees het collectiebeleidsplan: <a href="<?php echo $plan[3];?>"><?php echo $plan[2];?>, <?php echo $plan[0];?> - <?php echo $plan[1];?></a></p>
      <?php endforeach?>  
      <hr>
    <?php endif;?>  
       
    <?php if($type == "Sub-collection" || $type == "Collection focus"):?>    
      <h3 class="title is-5"><?php echo "Acquisitiebeleid";?></h3>     
      <p>De acquisitiestatus van de collectie is <?php echo $item->value("cw:colAccrualPolicy");?></p> 
      <p>Deze collectie wordt <?php echo $item->value("cw:colAccrualPeriodicity");?> aangevuld door:</p>
      <?php $methods = $item->value("cw:colAccrualMethod",['all' => true]); ?>
      <ul>
      <?php foreach($methods as $method):?>
        <li><?php echo $method->asHtml();?></li>
      <?php endforeach;?>  
      </ul>
      <hr>   
    <?php endif;?>
     
    <?php if($type == "Collection focus"):?>    
      <h3 class="title is-5"><?php echo "Doelstellingen";?></h3>     
      <?php $texts = $item->value("cw:colDevGoals",['all' => true]); ?>
      
      <?php foreach($texts as $text):?>
        <?php $texte = eplode("$$",$text->asHtml());?>
        <h4 class="title is-6"><?php echo array_shift($texte);?></h4>
        <?php foreach($texte as $text):?>
          <p><?php echo $text;?></p>
        <?php endforeach;?>
      <?php endforeach;?>        
    <?php endif;?>
    </div>
  </div>       
</section>
<?php
//idno -> 192
//isPartOf -> 235

//find sub-collections
$query = "";
parse_str("property[0][joiner]=and&property[0][property]=235&property[0][type]=eq&property[0][text]=".$item->value('cw:idno')."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
$subcollections = $this->api()->search('items',$query);
$subcollections = $subcollections->getContent();?>

<?php if($subcollections):?>
<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Onderliggende collecties";?></h2>
      <div class="columns" style="overflow:auto;">
        <?php foreach($subcollections as $subcollection):?>
          <?php if($subcollection->displayTitle() != $item->displayTitle()):?>
           <?php
            $media = $subcollection->primaryMedia();
            if($media):
              $url = str_replace('http:', '', $media->thumbnailUrl('square'));
            else: 
              $url = $defaultThumbnail;
            endif; 
            //$thumbnail = $media ? $thumbnailHelper($media, 'square') : $defaultThumbnail; 
           ?>      
           <div class="column is-2">
            <div class="">
              <a href="<?php echo $subcollection->url();?>"><img src="<?php echo $url;?>"></a>
            </div>   
            <div class="content resource-metadata-grid">
            <h5 class="title is-6" style="margin:1rem 0 0 0;"><a class="resource-link" href="<?php echo $subcollection->url();?>">
               <?php echo $subcollection->displayTitle();?>
              </a></h5>
            </div>
            <?php //echo $subcollection->displayTitle();?>
           </div>
          <?php endif;?> 
        <?php endforeach;?>
      </div> 
    </div>
  </div>
</section>
<?php endif;?>

<?php 
//find related collections
$relCols = $item->value("cw:associatedCollection",['all' => true]);
$relCols_a = [];$relCols_final = array();
foreach($relCols as $relCol):
  $relCols_a[$relCol->asHtml()] = $relCol->asHtml();
endforeach;

ksort($relCols_a);
foreach($relCols_a as $relCol):
  $query = "";
  parse_str("property[0][joiner]=and&property[0][property]=194&property[0][type]=eq&property[0][text]=".$relCol."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
  $rels = $this->api()->search('items',$query);
  $rels = $rels->getContent();
 
  if($rels):
    $relCols_final[$rels[0]->displayTitle()] = $rels[0];
  endif;  
endforeach;?>
<?php if($relCols_final):?>
<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Verwante collecties";?></h2>
      <div class="columns" style="overflow:auto;">
        <?php foreach($relCols_final as $subcollection):?>
           <?php
           $media = $subcollection->primaryMedia();
           if($media):
            $url = str_replace('http:', '', $media->thumbnailUrl('square'));
           else: 
            $url = $defaultThumbnail;
           endif; 
           ?>      
           <div class="column is-2">
            <div class="">
              <a href="<?php echo $subcollection->url();?>"><img src="<?php echo $url;?>"></a>
            </div>   
            <div class="content resource-metadata-grid">
            <h5 class="title is-6" style="margin:1rem 0 0 0;"><a class="resource-link" href="<?php echo $subcollection->url();?>">
               <?php echo $subcollection->displayTitle();?>
              </a></h5>
            </div>
            <?php //echo $subcollection->displayTitle();?>
           </div>
        <?php endforeach;?>
      </div> 
    </div>
  </div>
</section>
<?php endif;?>

<?php 
//find related collections
$relCols = $item->value("cw:isPartOfColFocus",['all' => true]);
$relCols_a = [];$relCols_final = [];
foreach($relCols as $relCol):
  $relCols_a[$relCol->asHtml()] = $relCol->asHtml();
endforeach;
ksort($relCols_a);
foreach($relCols_a as $relCol):
  $query = "";
  parse_str("property[0][joiner]=and&property[0][property]=194&property[0][type]=eq&property[0][text]=".$relCol."&resource_class_id[]=&resource_template_id[]=&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
  $rels = $this->api()->search('items',$query);
  $rels = $rels->getContent();
  if($rels):
    $relCols_final[] = $rels[0];
  endif;  
endforeach;?>
<?php if($relCols_final):?>
<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "De collectie draagt bij tot deze collectiefocussen";?></h2>
      <div class="columns" style="overflow:auto;">
        <?php foreach($relCols_final as $subcollection):?>
           <?php
           $media = $subcollection->primaryMedia();
           if($media):
            $url = str_replace('http:', '', $media->thumbnailUrl('square'));
           else: 
            $url = $defaultThumbnail;
           endif; 
           ?>      
           <div class="column is-2">
            <div class="">
            <a href="<?php echo $subcollection->url();?>"><img src="<?php echo $url;?>"></a>
            </div>   
            <div class="content resource-metadata-grid">
            <h5 class="title is-6" style="margin:1rem 0 0 0;"><a class="resource-link" href="<?php echo $subcollection->url();?>">
               <?php echo $subcollection->displayTitle();?>
              </a></h5>
            </div>
            <?php //echo $subcollection->displayTitle();?>
           </div>
        <?php endforeach;?>
      </div> 
    </div>
  </div>
</section>
<?php endif;?>

<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Meer weten?";?></h2>     
      <?php if($item->value("cw:isAlsoDescribedBy_Plus")):?>
        <p>Je vindt meer over deze collectie op:</p>
        <?php $plans = $item->value("cw:isAlsoDescribedBy_Plus",['all' => true]); ?>
        <?php foreach($plans as $plan):?>
          <?php $plan = explode("$$",$plan);?>
          <li><a href="<?php echo $plan[2];?>"><?php echo $plan[1];?></a></li>
        <?php endforeach?>  
        <hr>   
      <?php endif;?>   
     
      
      <?php if($item->value("cw:refersTo_Plus")):?>
        <p>Of neem een kijkje in de volgende publicatie(s):</p>
        <?php $plans = $item->value("cw:refersTo_Plus",['all' => true]); ?>
        <?php foreach($plans as $plan):?>
          <?php $plan = explode("$$",$plan);?>
          <li>
            <?php echo $plan[1];?>
            <?php if(isset($plan[2])):?>
              <?php if($plan[2]):?>
              (p.<?php echo $plan[2];?>
              <?php if(isset($plan[3])):?>
              , <?php echo $plan[3];?>
              <?php endif;?>  
              )
              <?php endif;?>
            <?php endif;?>  
          </li>
        <?php endforeach?>  
      <?php endif;?> 
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Vragen of feedback bij deze collectie?";?></h2>     
      <p>Heb je een vraag over deze collectie? <a href="">Stel ze aan de collectiebeheerder</a></p>
      <p>Heb je een aanvulling bij deze beschrijving? Merkte je foutieve of verouderde informatie op? <a href="">Laat het ons weten</a></p>
      <p>Deze beschrijving werd het laatst aangepast op ...</p>    
    </div>
  </div>
</section>

</div>

    </div>
  </div>                      
</section>
<?php endif;?>

<!-- ORGANISATION -->
<?php if($type == 'Organisation'):?>
  <section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8">
        <div class="columns">
          <?php if($itemMedia):?>
            <div class="column is-2">                
                <?php $url = str_replace('http:', '', $itemMedia[0]->thumbnailUrl('medium'));?>
                <img src="<?php echo $url;?>">                
            </div>
          <?php endif;?>   
          <div class="column">
            <h2 class="title is-2"><?php echo $item->displayTitle();?></h2>     
            <h3 class="subtitle is-5"><?php echo $item->value('cw:addressTown');?></h3>
          </div>
        </div>  
        <div class="box">
          <div class="columns">
          <?php if($item->value('cw:addressGeoNames')):?>
            <div class="column is-5">              
              <?php 
                $geo = $item->value('cw:addressGeoNames');
                preg_match_all('/\\[(.*?)\\]/',$geo,$matches);
                $geo = $matches[1][0];
              ?>
              <div id="map" style="width: 100%; height: 350px;"></div>                           
            </div>  
            <?php endif;?> 
            <div class="column">
              <p class="is-size-6">
                  <?php echo $item->value('cw:addressStreet')." ".$item->value('cw:addressNumber')." ".$item->value('cw:addressMailbox');?><br>
                  <?php echo $item->value('cw:addressPostalCode').", ".$item->value('cw:addressTown');?>
              </p>
            
              <?php if($item->value("cw:telephone")):?>
                <?php $tels = $item->value("cw:telephone",['all' => true]); ?>
                <?php foreach($tels as $tel):?>
                  <?php $tel = explode("$$",$tel);?>
                  <p>
                  <?php if(isset($tel[0])):?>
                    <?php echo $tel[0].": ";?>
                  <?php endif;?>  
                  <?php echo $tel[1];?>
                  <?php if(isset($tel[2])):?>
                    <?php echo " (".$tel[2].")";?>
                  <?php endif;?>  
                  </p>
                <?php endforeach?>  
              <?php endif;?> 
              <?php if($item->value("cw:website")):?>
                <?php $webs = $item->value("cw:website",['all' => true]); ?>
                <?php foreach($webs as $web):?>
                  <?php $web = explode("$$",$web);?>
                  <p>
                    <a href="<?php echo $web[1];?>"><?php echo $web[0];?></a>
                  </p>
                <?php endforeach?>  
              <?php endif;?> 
              <?php if($item->value("cw:email")):?>
                  <?php $mails = $item->value("cw:email",['all' => true]); ?>
                  <?php foreach($mails as $mail):?>
                    <?php $mail = explode("$$",$mail);?>
                    <p>
                      <a href="mailto:<?php echo $mail[0];?>"><?php echo $mail[0];?></a>
                      <?php if(isset($mail[1])):?>
                        (<?php echo $mail[1];?>)
                    <?php endif ;?>
                    </p>
                  <?php endforeach?>  
              <?php endif;?> 
              <?php if($item->value("cw:socialMedia")):?>
                <hr>
                  <h3 class="title is-5">Volg ons op</h3>
                  <?php $socials = $item->value("cw:socialMedia",['all' => true]); ?>
                  <?php foreach($socials as $social):?>
                    <?php $social = explode("$$",$social);?>
                      <a class="button" href="<?php echo $social[2];?>">
                        <span class="icon"><i class="fab fa-<?php echo strtolower($social[0]);?>"></i></span>
                        <span><?php echo $social[0];?></span>
                      </a>                    
                  <?php endforeach?>  
              <?php endif;?>
            </div">
          </div>         
        </div>
      </div>   
      <?php if($item->value("cw:colDescription")):?>
        <div class="column-4">
          <div class="box">
            <h2 class="title is-4"><?php echo "Welk erfgoed bewaren we?";?></h2>            
            <div class="content">
              <div class="text">
              <?php echo $item->value("cw:colDescription"); ?>
              </div>
            </div>
          </div>
        </div>      
      <?php endif;?>         
    </div>
  </div>
</section>

<?php
  //find sub-collections
  $query = "";
  parse_str("property[0][joiner]=and&property[0][property]=221&property[0][type]=eq&property[0][text]=".$item->value('cw:idno')."&resource_class_id[]=&resource_template_id[]=2&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
  $subcollections = $this->api()->search('items',$query);
  $subcollections = $subcollections->getContent();
?>

<?php if($subcollections):?>
<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Onze erfgoedcollecties";?></h2>
      <div class="columns" style="overflow:auto;">
        <?php foreach($subcollections as $subcollection):?>
           <?php
           $media = $subcollection->primaryMedia();
           if($media):
            $url = str_replace('http:', '', $media->thumbnailUrl('square'));
           else: 
            $url = $defaultThumbnail;
           endif; 
           //$thumbnail = $media ? $thumbnailHelper($media, 'square') : $defaultThumbnail; 
           ?>      
           <div class="column is-2">
            <div class="">
              <a href="<?php echo $subcollection->url();?>"><img src="<?php echo $url;?>"></a>
            </div>   
            <div class="content resource-metadata-grid">
            <h5 class="title is-6" style="margin:1rem 0 0 0;"><a class="resource-link" href="<?php echo $subcollection->url();?>">
               <?php echo $subcollection->displayTitle();?>
              </a></h5>
            </div>
            <?php //echo $subcollection->displayTitle();?>
           </div>
        <?php endforeach;?>
      </div> 
    </div>
  </div>
</section>
<?php endif;?>

<?php
  //find colfocus
  $query = "";
  parse_str("property[0][joiner]=and&property[0][property]=221&property[0][type]=eq&property[0][text]=".$item->value('cw:idno')."&resource_class_id[]=&resource_template_id[]=3&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
  $subcollections = $this->api()->search('items',$query);
  $subcollections = $subcollections->getContent();
?>

<?php if($subcollections):?>
<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Wat bewaren we?";?></h2>
      <div class="columns" style="overflow:auto;">
        <?php foreach($subcollections as $subcollection):?>
           <?php
           $media = $subcollection->primaryMedia();
           if($media):
            $url = str_replace('http:', '', $media->thumbnailUrl('square'));
           else: 
            $url = $defaultThumbnail;
           endif; 
           //$thumbnail = $media ? $thumbnailHelper($media, 'square') : $defaultThumbnail; 
           ?>      
           <div class="column is-2">
            <div class="">
              <a href="<?php echo $subcollection->url();?>"><img src="<?php echo $url;?>"></a>
            </div>   
            <div class="content resource-metadata-grid">
            <h5 class="title is-6" style="margin:1rem 0 0 0;"><a class="resource-link" href="<?php echo $subcollection->url();?>">
               <?php echo $subcollection->displayTitle();?>
              </a></h5>
            </div>
            <?php //echo $subcollection->displayTitle();?>
           </div>
        <?php endforeach;?>
      </div> 
    </div>
  </div>
</section>
<?php endif;?>

<section class="section">
  <div class="container">
    <div class="box">
      <h2 class="title is-4"><?php echo "Een aanpassing voorstellen?";?></h2>      <p>Heb je een aanvulling bij deze beschrijving? Merkte je foutieve of verouderde informatie op? <a href="">Laat het ons weten</a></p>
      <p>Deze beschrijving werd het laatst aangepast op ...</p>    
    </div>
  </div>
</section>

<?php endif;?>  

<?php
//find collections
$query = "";
parse_str("property[0][joiner]=and&property[0][property]=192&property[0][type]=eq&property[0][text]=".$item->value('cw:idno')."&resource_class_id[]=&resource_template_id[]=3&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
$containers = $this->api()->search('items',$query);
$containers = $containers->getContent();
?>
<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
<script>
  //
  if (location.hash) {
    
    var hash = $(location).attr('hash');
    window.location.hash = "";
    $(hash).find(".content").show();
        $(hash).addClass('open');
    
    setTimeout(function() { 
      var pos = $(hash).offset().top;
    $('body, html').animate({scrollTop: pos-66});
    window.location.hash = hash;
    }, 500);
  }
  $(document).ready(function(){

    <?php if(isset($geo)):?>
    var map = L.map('map').setView([<?php echo $geo;?>], 12);
    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 18,
      id: 'mapbox/streets-v11',
      tileSize: 512,
      zoomOffset: -1,
      accessToken: 'pk.eyJ1Ijoiam9yaXNsaWJpcyIsImEiOiJja3g0cjFzdGcweTBoMm5xa3Y3N3BweXNuIn0.B7FndQiqXpfd_Fwhjc64DA'
    }).addTo(map);
    var marker = L.marker([<?php echo $geo;?>]).addTo(map);
    <?php endif;?>




    $('.opener').click(function(e){
      e.preventDefault();
      $(this).parent().next(".content").toggle();
      $(this).parent().parent().toggleClass('open');
    });

    $('.floating-nav a').click(function(e){
      //e.preventDefault();
      
      var id = $(this).attr('href');      
      id = id.replace('#','');
      window.location.hash = id;
      var elem = document.getElementById(id);
     
      //elem.scrollIntoView(true);

      var pos = $($(this).attr('href')).offset().top;
      $('body, html').animate({scrollTop: pos - 66});
      
      $($(this).attr('href')).find(".content").show();
      $($(this).attr('href')).addClass('open');

    });

    $('.text').each(function(){
      if($(this).height() > 100){
        $(this).readmore({ speed: 75, collapsedHeight: 100, moreLink: '<a class="more-link" href="#">Read more</a>', lessLink: '<a class="more-link" href="#">Read less</a>' });;
      }      
    });
    
    

    $('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: false,
      fade: true,
      centerMode: true,
      asNavFor: '.slider-nav'
    });
    
    $('.slider-nav').slick({
      slidesToShow: 6,
      slidesToScroll: 1,
      asNavFor: '.slider-for',
      focusOnSelect: true
    });

    var quickLinks = document.querySelectorAll(".floating-nav a");
    var	positionArray =[], hashArray = [];

    for (var i=0; i<quickLinks.length; i++){
    	hashArray.push(quickLinks[i].href.substring(quickLinks[i].href.indexOf('#')+1));
    }

    for (var i=0; i<hashArray.length; i++){
    	positionArray.push(document.getElementById(hashArray[i]).getBoundingClientRect().top);
    }

    function isActive1(){
    	document.getElementsByClassName('is-active')[0];
    }

    document.addEventListener("scroll", scrollHandler, true);

    function scrollHandler() {
    	currentScrollPosition = document.documentElement.scrollTop;
    	//currentActivePosition = document.getElementsByClassName('is-active')[0].getBoundingClientRect().top;
    	for (var i=1; i<=positionArray.length; i++){
    		if (currentScrollPosition>=positionArray[i-1] && currentScrollPosition < positionArray[i]) {
    			var currentActive = document.getElementsByClassName('is-active')[0];
    				if (currentActive != undefined){
        			currentActive.classList.remove('is-active');
        		}
	        quickLinks[i-1].classList.add('is-active');
  			  break;
  		  }

    		if (currentScrollPosition>positionArray[positionArray.length-1]){
    			var currentActive = document.getElementsByClassName('is-active');
  				var currentActive = document.getElementsByClassName('is-active')[0];
  				if (currentActive != undefined){
      			currentActive.classList.remove('is-active');
    			}
    			quickLinks[quickLinks.length-1].classList.add('is-active');
    			break;
  		 }
  	  }
    };

    for (var i=0; i<quickLinks.length; i++){
    	quickLinks[i].addEventListener('click', function(event){
    		document.removeEventListener('scroll', scrollHandler, true);

    		/**
    		for (var j=0; j<quickLinks.length; j++){
    			if (quickLinks[j].classList.contains('is-active')){
    				quickLinks[j].classList.remove('is-active');
    			}
    		}
    		**/

    		isActive = document.getElementsByClassName('is-active')[0];

    		if (isActive != undefined){
    			isActive.classList.remove('is-active');
    		}

    		this.classList.add('is-active');
    		setTimeout(function(){
        			document.addEventListener("scroll", scrollHandler, true);
    	}, 600);
    	});
    }
  });
</script>
<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
     integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
     crossorigin=""></script>