<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var string $value
 * @var string $label
 * @var int $count
 * @var bool $active
 * @var string $url
 * @var \Zend\View\Helper\EscapeHtml $escapeHtml
 */
?>

<span class="<?= $active ? 'active' : 'inactive' ?>">
    <?php if($count != 0):?>
        <a href="<?= $escapeHtml($url) ?>"><?= $escapeHtml($label) ?> (<?= $count ?>)</a>  
    <?php elseif($count == 0 && $active):?>
        <a style="color:#777;" href="<?= $escapeHtml($url) ?>"><?= $escapeHtml($label) ?> (<?= $count ?>)</a>      
    <?php else:?>
        <a style="color:#777;" href="<?= $escapeHtml($url) ?>"><?= $escapeHtml($label) ?></a>  
    <?php endif;?>        
</span>
