<?php
$translate = $this->plugin('translate');
?>
<nav class="pagination" role="navigation" aria-label="pagination">
<?php if ($totalCount): ?>


    <form method="GET" action="">
        <?php echo $this->queryToHiddenInputs(['page']); ?>
        <input style="width:30%;" type="text" name="page" class="page-input-top" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?> aria-label="<?php echo $translate('Page'); ?>">
        <span class="page-count"><?php echo sprintf($translate('van de %s'), $pageCount); ?></span>
        <?php
        $from = $offset + 1;
        $to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
        ?>
        <span class="row-count" style="color:#666;">(<?php echo sprintf($translate('%1$s–%2$s of %3$s'), $from, $to, $totalCount); ?>)</span>
    
    </form>

    <div style="padding-top: 5%;">
    <?php if ($currentPage != 1): ?>
    <?php echo $this->hyperlink($translate('Vorige'), $previousPageUrl, ['class' => 'pagination-previous btn btn-primary', 'title' => $translate('Previous'), 'aria-label' => $translate('Previous')]); ?>
    <?php endif; ?>
    <?php if ($currentPage < $pageCount): ?>
    <?php echo $this->hyperlink($translate('Volgende'), $nextPageUrl, ['class' => 'pagination-next btn btn-primary', 'title' => $translate('Next'), 'aria-label' => $translate('Next')]); ?>
    <?php endif; ?>
    </div>


<?php else: ?>
    <?php echo $translate('0 resultaten'); ?>
<?php endif; ?>
</nav>
