<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$not = array('korte beschrijving','vindplaats','vindplaats Brussel');
$notalt = array('korte beschrijving', 'Collectie ID','Referenties object','Beeld','Beeld copyright');
?>

<?php foreach ($templateProperties as $term => $property): ?>
  <?php 
    if($property->isPrivate()):
      continue;
    endif;
    $propertyData = '';
    if(isset($values[$property->property()->term()])):
      $propertyData = $values[$property->property()->term()];
    else:
      continue;
    endif;
  ?>  


  <?php if(!in_array($propertyData['property']->label(),$not) && !in_array($propertyData['alternate_label'],$notalt)):?>
  <div class="row">
    <div class="col-xs-12 col-md-3">
      <h4 class="title is-6" style="font-size:0.9rem;padding-top:0.3rem;padding-bottom:0.3rem;line-height: 1.6;padding-left:10%;<?php if($propertyData['alternate_label'] == 'bijkomende info'):?>margin-left:5%;<?php endif?>">
      <?php if ($propertyData['alternate_label']): ?>
      <?php echo $escape($propertyData['alternate_label']); ?>
      <?php else: ?>
      <?php echo $escape($translate($propertyData['property']->label())); ?>
      <?php endif; ?>
      <?php if ('term' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
      <?php elseif ('vocab' === $labelInfo): ?>
      <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
      <?php endif; ?>
      </h4>
    </div>
    <div class="col-xs-12 col-md-9">
      <div class="values" style="font-size:0.9rem;padding-top:0.3rem;padding-bottom:0.3rem;padding-right:3%;padding-left:1%;line-height: 1.6;">
      <?php $i=0;
      $g=0;
      if($propertyData['property']->label() == 'staalnummer(s)'):
      ?>
      <div class="row">
        <div class="col-2">
      <?php endif;?>
      <?php foreach ($propertyData['values'] as $value): ?>
          <?php
          $valueType = $value->type();
          $class = ['value'];
          if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
              $class[] = 'resource';
              $class[] = $escape($value->valueResource()->resourceName());
          } elseif ('uri' == $valueType) {
              $class[] = 'uri';
          }
          if (!$value->isPublic()) {
              $class[] = 'private';
          }
          ?>
            <?php if($g > 4):?>
            </div>
            <div class="col-2">
              <?php 
            $g = 0;
            endif;?>

            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?php echo $language; ?></span>
                <?php endif; ?>
                <?php if($propertyData['property']->label() == 'staalnummer(s)'):
                $g++;
                echo $value->asHtml();
                ?>
                <?php elseif($propertyData['property']->label() == 'categorie'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:categorie][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['property']->label() == 'materiaalsoort'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:materiaalsoort][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['property']->label() == 'toepassingen'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:toepassingen][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['property']->label() == 'samenstelling'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:samenstelling][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['property']->label() == 'gerecycleerde grondstof'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:gerecycleerdeGrondstof][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['property']->label() == 'duurzaamheidslabel(s)'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:duurzaamheidslabel][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['property']->label() == 'levenscyclus - oorsprong'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:levenscyclusOorsprong][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['property']->label() == 'waterafstotend'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:waterafstotend][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php elseif($propertyData['property']->label() == 'akoestisch - absorberend'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:akoestischAbsorberend][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'akoestisch - isolerend'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:akoestischIsolerend][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'elektrische weerstand'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:elektrischeWeerstand][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'optisch - lichtreflectie'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:optischLichtreflectie][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'optisch - transparantie'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:optischTransparantie][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'UV-bestendig'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:uvbestendig][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'levenscyclus - afvalfase'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:levenscyclusAfvalfase][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'EPD (Environmental Product Declaration)'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:epd][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'insectenbestendig'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:insectenbestendig][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'krasbestendig'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:krasbestendig][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'chemisch bestendig'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:chemischbestendig][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'corrosiebestendig'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:corrosiebestendig][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'vorstbestendig'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:vorstbestendig][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'vochtbestendig'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:vochtbestendig][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'schimmelbestendig'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:schimmelbestendig][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                  <?php elseif($propertyData['property']->label() == 'brandvertragend'):?>
                  <a target="_blank" href="/materialendatabank/s/tdc/find?facet[tdc:brandvertragend][]=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php else:?>
                  <?php echo $value->asHtml(); ?>
                <?php endif;?>
            </div>
            <?php $i++;?>
      <?php endforeach; ?>
      </div>
      <?php
      if($propertyData['property']->label() == 'staalnummer(s)'):
      ?>
    </div>
      </div>
      <?php endif;?>
    </div>
  </div>
  <?php endif;?>
<?php endforeach; ?>