<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Entity\User|null $user
 * @var \Contribute\Form\ContributeForm $form
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var array $fields
 * @var \Omeka\Api\Representation\ResourceTemplateRepresentation $templateMedia A sub template for media may have no fields.
 * @var array $fieldsByMedia
 * @var array $fieldsMediaBase
 * @var string $action "add" or "edit" or "show"
 * @var string $mode "read" (for template select or for show readonly form before submit) or "write"
 * @var string $space "default" or "guest"
 */

$plugins = $this->getHelperPluginManager();
$setting = $plugins->get('setting');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$contributionForm = $plugins->get('contributionForm');

$this->htmlElement('body')->appendAttribute('class', 'edit items ' . $this->params()->fromRoute('resource') . ' resource');

if ($form) $form->prepare();

$mapLabels = [
    'contributions' => 'item',
    'items' => 'item',
    'media' => 'media',
    'item_sets' => 'item set',
];
?>

<div class="contribute-resource conbribute-add container <?= $space && $space !== 'default' ? $space : '' ?>">

    <h1>Materiaalsuggestie</h1>

    <div class="row">
        <div class="kul-card-color card card-gray col-md-12">
            <div class="card-body">
            U bent fabrikant en wenst een materiaal te laten opnemen in deze materialendatabank voor toekomstige ingenieurs, architecten en interieurarchitecten/vormgevers. 
            Hiervoor lever je een fysiek materiaal af bij de Faculteit Industriële Ingenieurswetenschappen KU Leuven Gent op Campus Rabot en bij de Faculteit Architectuur - KU Leuven Gent op de Campus Sint-Lucas Gent (zie <a href="https://bib.kuleuven.be/materialendatabank/s/tdc/page/contact">contact</a>), vul je onderstaand formulier correct in en lever je de correcte linken aan naar de gevraagde attesten.
            </div>
        </div>
    </div>

    <div class="messages">
        <?= $this->messages() ?>
    </div>

    <?php if (count($fields) && $form):
        // The two lists of fields are merged in one form by default.
        $this->trigger("view.$action.before");
        echo $contributionForm([
            'site' => $site,
            'user' => $user,
            'form' => $form,
            'contribution' => $contribution,
            'resource' => $resource,
            'fields' => $fields,
            'templateMedia' => $templateMedia,
            'fieldsByMedia' => $fieldsByMedia,
            'fieldsMediaBase' => $fieldsMediaBase,
            'action' => $action,
            'mode' => $mode,
            'space' => $space,
            'submitLabel' => $action === 'add' && $setting('contribute_allow_update') !== 'no' ? $translate('Verzenden') : $translate('Submit'),
            'cancelLabel' => $translate('Invoer wissen'),
            'isMainForm' => true,
            'skipContributeCss' => false,
        ]);
        $this->trigger("view.$action.after");

    elseif ($action === 'add' && $form): // First step form to select a resource template.
        if ($mode === 'read') {
            $form->remove('submit');
            echo $this->form($form);
        } else {
            $form->get('submit')->setValue('Select'); // @translate
            echo $this->form($form);
        }

    else: ?>
    <div class="messages">
        <p><?= $translate('A template with fields is required to submit a document. Ask the administrator for more information.') ?></p>
    </div>

    <?php endif; ?>

</div>
